# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HH6S9uNxxF1_KFe255T5Y4wl0NhhxaVw
"""

import heapq

# -----------------------------
# Union-Find (Disjoint Set)
# -----------------------------
class UnionFind:
    def __init__(self, n):
        self.parent = list(range(n))
        self.rank = [0] * n

    def find(self, x):
        if self.parent[x] != x:
            self.parent[x] = self.find(self.parent[x])  # Path Compression
        return self.parent[x]

    def union(self, x, y):
        root_x = self.find(x)
        root_y = self.find(y)

        if root_x == root_y:
            return False

        # Union by Rank
        if self.rank[root_x] < self.rank[root_y]:
            root_x, root_y = root_y, root_x

        self.parent[root_y] = root_x

        if self.rank[root_x] == self.rank[root_y]:
            self.rank[root_x] += 1

        return True


# -----------------------------
# Kruskal's Algorithm
# -----------------------------
def kruskal(n, edges):
    """
    n = number of vertices
    edges = [(weight, u, v), ...]
    """
    edges.sort()  # Sort edges by weight

    uf = UnionFind(n)
    mst = []
    total_cost = 0

    for weight, u, v in edges:
        if uf.union(u, v):
            mst.append((u, v, weight))
            total_cost += weight

            if len(mst) == n - 1:
                break

    return mst, total_cost


# -----------------------------
# Prim's Algorithm
# -----------------------------
def prim(n, adj, start=0):
    """
    adj = {
        vertex: [(neighbor, weight), ...]
    }
    """
    visited = [False] * n
    min_heap = [(0, start, -1)]  # (weight, current, parent)

    mst = []
    total_cost = 0

    while min_heap:
        weight, current, parent = heapq.heappop(min_heap)

        if visited[current]:
            continue

        visited[current] = True

        if parent != -1:
            mst.append((parent, current, weight))
            total_cost += weight

        for neighbor, edge_weight in adj.get(current, []):
            if not visited[neighbor]:
                heapq.heappush(
                    min_heap,
                    (edge_weight, neighbor, current)
                )

    return mst, total_cost


# -----------------------------
# Driver Code
# -----------------------------
n = 7

edges = [
    (7, 0, 1),
    (5, 0, 3),
    (8, 1, 2),
    (9, 1, 3),
    (7, 1, 4),
    (5, 2, 4),
    (15, 3, 4),
    (6, 3, 5),
    (8, 4, 5),
    (9, 4, 6),
    (11, 5, 6)
]

# Build adjacency list for Prim's Algorithm
adj = {}

for weight, u, v in edges:
    adj.setdefault(u, []).append((v, weight))
    adj.setdefault(v, []).append((u, weight))

# Run Kruskal's Algorithm
kruskal_mst, kruskal_cost = kruskal(n, edges.copy())

# Run Prim's Algorithm
prim_mst, prim_cost = prim(n, adj)

# -----------------------------
# Output
# -----------------------------
print("=== Kruskal's MST ===")
for u, v, weight in kruskal_mst:
    print(f"Edge ({u} - {v}) Weight: {weight}")
print("Total MST Cost:", kruskal_cost)

print("\n=== Prim's MST ===")
for u, v, weight in prim_mst:
    print(f"Edge ({u} - {v}) Weight: {weight}")
print("Total MST Cost:", prim_cost)